# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kenneth.io
title: Kenneth Auchenberg
subtitle: Passion for the web platform.
author: Kenneth Auchenberg
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"
excerpt_separator: <!--more-->

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: _site
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
paginate: 5          # Posts per page on the blog index
paginate_path: "blog/page/:num"  # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: auchenberg
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: blog-kenneth-io
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:


assets:
  # cachebust: none
  cache_assets: false
  compress:
    css:  sass
    js:   uglifier

  sources:
    - _assets/
    - _assets/bower_components
    - _assets/javascripts
    - _assets/stylesheets

